version: "3"

services:
  app:
    build:
      context: .
    command: yarn run dev
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
      - node_modules:/usr/src/app/node_modules

volumes:
  node_modules:
    driver: local
