import Head from "next/head";

export default function Page() {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta content="Generated by create next app" name="description" />
				<meta content="width=device-width, initial-scale=1" name="viewport" />
			</Head>
			<div>Hello, World!</div>
		</>
	);
}
